Feature setup partials
AWTION/New-Sethi-Cloth-House pull request #1
Opened 2023-10-24 20:34 UTC by EstefaniaCK

Hi Harsh, 

Please review and merge the pull request. 

Thanks,

2023-10-24 21:57 UTC, mandeepharsh commented
Good work estefania

2023-10-24 21:59 UTC, mandeepharsh requested changes
We should download the fonts instead of importing them from google

2023-10-24 22:01 UTC, mandeepharsh commented on src/styles/partials/color.scss
We should not reference the color itself while naming it, instead we should refrence what that color will be used for, so if we need to change the color in the future we don't have to change the name of the variable everywhere

2023-10-24 22:02 UTC, mandeepharsh requested changes
@EstefaniaCK We should not reference the color itself while naming it, instead we should refrence what that color will be used for, so if we need to change the color in the future we don't have to change the name of the variable everywhere

2023-10-31 16:35 UTC, EstefaniaCK commented
Hi Harsh, 

as discussed fonts have been downloaded and color names have been updated. 

If there is anything else please let me know

2023-10-31 16:35 UTC, mandeepharsh approved these changes
Great work!!

2023-10-31 16:35 UTC, merged